module.exports = new Map([
  [0, 'Tape mount'],
  [1, 'Tape position'],
  [2, 'Connect'],
  [3, 'Write'],
  [4, 'Choose image'],
  [5, 'Duplicate image'],
  [6, 'Choose media'],
  [7, 'Catalog'],
  [8, 'Tape eject'],
  [10, 'Read'],
  [11, 'Duplicate'],
  [12, 'Import'],
  [13, 'Verify'],
  [14, 'Restore'],
  [15, 'Catalog backup'],
  [16, 'Vault'],
  [17, 'Label tape'],
  [18, 'Erase tape'],
  [19, 'Query database'],
  [20, 'Process extents'],
  [21, 'Organize readers'],
  [22, 'Create snapshot'],
  [23, 'Delete snapshot'],
  [24, 'Recover DB'],
  [25, 'Media contents'],
  [26, 'Request job resources'],
  [27, 'Parent job'],
  [28, 'Indexing'],
  [29, 'Duplicate to RM'],
  [30, 'Running'],
]);
