module.exports = new Map([
  [0, 'Backup'],
  [1, 'Archive'],
  [2, 'Restore'],
  [3, 'Verify'],
  [4, 'Duplicate'],
  [5, 'Import'],
  [6, 'Catalog backup'],
  [7, 'Vault duplicate'],
  [8, 'Label tape'],
  [9, 'Erase tape'],
  [10, 'Tape request'],
  [11, 'Clean tape'],
  [12, 'Format tape'],
  [13, 'Inventory'],
  [14, 'Test'],
  [15, 'Catalog Recovery'],
  [16, 'Media contents'],
  [17, 'Image cleanup'],
  [18, 'Live update'],
  [20, 'Replication (AIR)'],
  [21, 'Import (AIR)'],
  [22, 'Backup (Snap)'],
  [23, 'Replication (Snap)'],
  [24, 'Import (Snap)'],
  [25, 'ASC'],
  [26, 'Index'],
  [27, 'Index'],
  [28, 'Snapshot'],
  [29, 'Index (Snap)'],
  [30, 'Aactivate IR'],
  [31, 'Deactivate IR'],
  [32, 'Reactivate IR'],
  [33, 'Stop IR'],
  [34, 'IR'],
]);
