module.exports = new Map([
  [0, 'UX'],
  [1, 'Proxy'],
  [4, 'Oracle'],
  [6, 'Informix'],
  [7, 'Sybase'],
  [8, 'MS-SharePoint'],
  [11, 'DT-SQL'],
  [13, 'MS-Windows'],
  [15, 'MS-SQL'],
  [16, 'MS-Exchange'],
  [17, 'SAP'],
  [18, 'DB2'],
  [19, 'NDMP'],
  [20, 'FlashBackup'],
  [21, 'SplitMirror'],
  [25, 'Lotus'],
  [29, 'FlashBackup-Windows'],
  [30, 'Vault'],
  [35, 'NBU-Catalog'],
  [36, 'Generic'],
  [38, 'PureDisk'],
  [39, 'EnterpriseVault'],
  [40, 'VMWare'],
  [41, 'Hyper-V'],
  [44, 'BigData'],
  [46, 'Deployment'],
]);
