module.exports = new Map([
  [0, 'the requested operation was successfully completed'],
  [1, 'The requested operation was partially successful'],
  [2, 'none of the requested files were backed up'],
  [
    3,
    'valid archive image produced, but no files deleted due to non-fatal problems',
  ],
  [4, 'archive file removal failed'],
  [5, 'the restore failed to recover the requested files'],
  [6, 'the backup failed to back up the requested files'],
  [7, 'the archive failed to back up the requested files'],
  [8, 'unable to determine the status of rbak'],
  [
    9,
    'a necessary extension package is not installed or not configured properly',
  ],
  [10, 'allocation failed'],
  [11, 'system call failed'],
  [12, 'file open failed'],
  [13, 'file read failed'],
  [14, 'file write failed'],
  [15, 'file close failed'],
  [16, 'unimplemented feature'],
  [17, 'pipe open failed'],
  [18, 'pipe close failed'],
  [19, 'getservbyname failed'],
  [20, 'invalid command parameter'],
  [21, 'socket open failed'],
  [22, 'socket close failed'],
  [23, 'socket read failed'],
  [24, 'socket write failed'],
  [25, 'cannot connect on socket'],
  [26, 'client/server handshaking failed'],
  [27, 'child process killed by signal'],
  [28, 'failed trying to fork a process'],
  [29, 'failed trying to exec a command'],
  [30, 'cannot get password information'],
  [31, 'could not set user ID for process'],
  [32, 'could not set group ID for process'],
  [33, 'failed while trying to send mail'],
  [34, 'failed waiting for child process'],
  [35, 'cannot make required directory'],
  [36, 'failed trying to allocate memory'],
  [37, 'operation requested by an invalid server'],
  [38, 'could not get group information'],
  [39, 'client name mismatch'],
  [40, 'network connection broken'],
  [41, 'network connection timed out'],
  [42, 'network read failed'],
  [43, 'unexpected message received'],
  [44, 'network write failed'],
  [45, 'request attempted on a non-reserved port'],
  [46, 'server not allowed access'],
  [47, 'host is unreachable'],
  [48, 'client hostname could not be found'],
  [49, 'client did not start'],
  [50, 'client process aborted'],
  [51, 'timed out waiting for database information'],
  [52, 'timed out waiting for media manager to mount volume'],
  [53, 'backup restore manager failed to read the file list'],
  [54, 'timed out connecting to client'],
  [55, 'permission denied by client during rcmd'],
  [56, "client's network is unreachable"],
  [57, 'client connection refused'],
  [58, "can't connect to client"],
  [59, 'access to the client was not allowed'],
  [60, 'client cannot read the mount table'],
  [63, 'process was killed by a signal'],
  [64, 'timed out waiting for the client backup to start'],
  [
    65,
    'client timed out waiting for the continue message from the media manager',
  ],
  [66, 'client backup failed to receive the CONTINUE BACKUP message'],
  [67, 'client backup failed to read the file list'],
  [68, 'client timed out waiting for the file list'],
  [69, 'invalid filelist specification'],
  [70, 'an entry in the filelist expanded to too many characters'],
  [71, 'none of the files in the file list exist'],
  [72, 'the client type is incorrect in the configuration database'],
  [73, 'bpstart_notify failed'],
  [74, 'client timed out waiting for bpstart_notify to complete'],
  [75, 'client timed out waiting for bpend_notify to complete'],
  [76, 'client timed out reading file'],
  [77, 'execution of the specified system command returned a nonzero status'],
  [78, 'afs/dfs command failed'],
  [79, 'unsupported image format for the requested database query'],
  [80, 'Media Manager device daemon (ltid) is not active'],
  [81, 'Media Manager volume daemon (vmd) is not active'],
  [82, 'media manager killed by signal'],
  [83, 'media open error'],
  [84, 'media write error'],
  [85, 'media read error'],
  [86, 'media position error'],
  [87, 'media close error'],
  [89, 'problems encountered during setup of shared memory'],
  [90, 'media manager received no data for backup image'],
  [91, 'fatal NB media database error'],
  [92, 'media manager detected image that was not in tar format'],
  [93, 'media manager found wrong tape in drive'],
  [94, 'cannot position to correct image'],
  [95, 'Media ID is not assigned to this host in the EMM database'],
  [
    96,
    'unable to allocate new media for backup, storage unit has none available',
  ],
  [97, 'requested media ID is in use, cannot process request'],
  [98, 'error requesting media (tpreq)'],
  [99, 'NDMP backup failure'],
  [100, 'system error occurred while processing user command'],
  [101, 'failed opening mail pipe'],
  [102, 'failed closing mail pipe'],
  [103, 'error occurred during initialization, check configuration file'],
  [104, 'invalid file pathname'],
  [105, 'file pathname exceeds the maximum length allowed'],
  [106, 'invalid file pathname found, cannot process request'],
  [108, 'Action succeeded but auditing failed'],
  [109, 'invalid date specified'],
  [110, 'Cannot find the NetBackup configuration information'],
  [111, 'No entry was found in the server list'],
  [112, 'no files specified in the file list'],
  [114, 'unimplemented error code'],
  [116, 'VxSS authentication failed'],
  [117, 'VxSS access denied'],
  [118, 'VxSS authorization failed'],
  [
    120,
    'cannot find configuration database record for requested NB database backup',
  ],
  [121, 'no media is defined for the requested NB database backup'],
  [122, 'specified device path does not exist'],
  [123, 'specified disk path is not a directory'],
  [124, 'NB database backup failed, a path was not found or is inaccessible'],
  [125, 'a NetBackup catalog backup is in progress'],
  [126, 'NB database backup header is too large, too many paths specified'],
  [
    127,
    'specified media or path does not contain a valid NB database backup header',
  ],
  [
    128,
    'NB database recovery failed, a process has encountered an exceptional condition',
  ],
  [129, 'Disk storage unit is full'],
  [130, 'system error occurred'],
  [131, 'client is not validated to use the server'],
  [132, 'user is not validated to use the server from this client'],
  [133, 'invalid request'],
  [134, 'unable to process request because the server resources are busy'],
  [135, 'client is not validated to perform the requested operation'],
  [136, 'tir info was pruned from the image file'],
  [140, 'User ID was not superuser'],
  [141, 'file path specified is not absolute'],
  [142, 'file does not exist'],
  [143, 'invalid command protocol'],
  [144, 'invalid command usage'],
  [145, 'daemon is already running'],
  [146, 'cannot get a bound socket'],
  [147, 'required or specified copy was not found'],
  [148, 'daemon fork failed'],
  [149, 'master server request failed'],
  [150, 'termination requested by administrator'],
  [152, 'required value not set'],
  [153, 'server is not the master server'],
  [154, 'storage unit characteristics mismatched to request'],
  [155, 'disk is full'],
  [156, 'snapshot error encountered'],
  [157, 'suspend requested by administrator'],
  [158, 'failed accessing daemon lock file'],
  [159, 'licensed use has been exceeded'],
  [160, 'authentication failed'],
  [161, 'Evaluation software has expired'],
  [162, 'incorrect server platform for license'],
  [163, 'media block size changed prior resume'],
  [
    164,
    'unable to mount media because it is in a DOWN, or otherwise not available',
  ],
  [
    165,
    'NB image database contains no image fragments for requested backup id/copy number',
  ],
  [166, 'backups are not allowed to span media'],
  [167, 'cannot find requested volume pool in EMM database'],
  [168, 'cannot overwrite media, data on it is protected'],
  [169, 'Media ID is either expired or will exceed maximum mounts'],
  [170, 'third party copy backup failure'],
  [171, 'media id must be 6 or less characters'],
  [172, 'cannot read media header, may not be NetBackup media or is corrupted'],
  [173, 'cannot read backup header, media may be corrupted'],
  [174, 'media manager - system error occurred'],
  [175, 'not all requested files were restored'],
  [176, 'cannot perform specified media import operation'],
  [177, 'could not deassign media due to Media Manager error'],
  [178, 'Media ID is not in NetBackup volume pool'],
  [179, 'density is incorrect for the media ID'],
  [180, 'tar was successful'],
  [181, 'tar received an invalid argument'],
  [182, 'tar received an invalid file name'],
  [183, 'tar received an invalid archive'],
  [184, 'tar had an unexpected error'],
  [185, 'tar did not find all the files to be restored'],
  [186, 'tar received no data'],
  [189, "the server is not allowed to write to the client's file systems"],
  [190, 'found no images or media matching the selection criteria'],
  [191, 'no images were successfully processed'],
  [192, 'VxSS authentication is required but not available'],
  [193, 'VxSS authentication is requested but not allowed'],
  [194, 'the maximum number of jobs per client is set to 0'],
  [195, 'client backup was not attempted'],
  [196, 'client backup was not attempted because backup window closed'],
  [197, 'the specified schedule does not exist in the specified policy'],
  [
    198,
    'no active policies contain schedules of the requested type for this client',
  ],
  [199, 'operation not allowed during this time period'],
  [200, 'scheduler found no backups due to run'],
  [201, 'handshaking failed with server backup restore manager'],
  [202, 'timed out connecting to server backup restore manager'],
  [203, "server backup restore manager's network is unreachable"],
  [204, 'connection refused by server backup restore manager'],
  [205, 'cannot connect to server backup restore manager'],
  [206, 'access to server backup restore manager denied'],
  [207, 'error obtaining date of last backup for client'],
  [209, 'error creating or getting message queue'],
  [210, 'error receiving information on message queue'],
  [212, 'error sending information on message queue'],
  [213, 'no storage units available for use'],
  [215, 'failed reading global config database information'],
  [216, 'failed reading retention database information'],
  [217, 'failed reading storage unit database information'],
  [218, 'failed reading policy database information'],
  [219, 'the required storage unit is unavailable'],
  [220, 'database system error'],
  [221, 'continue'],
  [222, 'done'],
  [223, 'an invalid entry was encountered'],
  [224, 'there was a conflicting specification'],
  [225, 'text exceeded allowed length'],
  [226, 'the entity already exists'],
  [227, 'no entity was found'],
  [228, 'unable to process request'],
  [229, 'events out of sequence - image inconsistency'],
  [230, 'the specified policy does not exist in the configuration database'],
  [231, 'schedule windows overlap'],
  [232, 'a protocol error has occurred'],
  [233, 'premature eof encountered'],
  [234, 'communication interrupted'],
  [235, 'inadequate buffer space'],
  [
    236,
    'the specified client does not exist in an active policy within the configuration database',
  ],
  [
    237,
    'the specified schedule does not exist in an active policy in the configuration database',
  ],
  [238, 'the database contains conflicting or erroneous entries'],
  [239, 'the specified client does not exist in the specified policy'],
  [240, 'no schedules of the correct type exist in this policy'],
  [241, 'the specified schedule is the wrong type for this request'],
  [242, 'operation would cause an illegal duplication'],
  [243, 'the client is not in the configuration'],
  [245, 'the specified policy is not of the correct client type'],
  [
    246,
    'no active policies in the configuration database are of the correct client type',
  ],
  [247, 'the specified policy is not active'],
  [248, 'there are no active policies in the configuration database'],
  [249, 'the file list is incomplete'],
  [250, 'the image was not created with TIR information'],
  [251, 'the tir information is zero length'],
  [252, 'An extended error status has been encountered, check detailed status'],
  [253, 'the catalog image .f file has been archived'],
  [254, 'server name not found in the NetBackup configuration'],
  [256, 'logic error encountered'],
  [257, 'failed to get job data'],
  [258, 'Vault duplication was aborted by administrator request'],
  [259, 'vault configuration file not found'],
  [260, 'failed to send signal'],
  [261, 'vault internal error 261'],
  [262, 'vault internal error 262'],
  [263, 'session ID assignment failed'],
  [265, 'session ID file is empty or corrupt'],
  [266, 'cannot find robot, vault, or profile in the vault configuration'],
  [267, 'cannot find the local host name'],
  [268, 'the vault session directory is either missing or inaccessible'],
  [269, 'no vault session id was found'],
  [270, 'unable to obtain process id, getpid failed'],
  [271, 'vault XML version mismatch'],
  [272, 'execution of a vault notify script failed'],
  [273, 'invalid job id'],
  [274, 'no profile was specified'],
  [275, 'a session is already running for this vault'],
  [276, 'invalid session ID'],
  [277, 'unable to print reports'],
  [278, 'unable to collect pre eject information from the API'],
  [279, 'eject process is complete'],
  [280, 'there are no volumes to eject'],
  [281, 'vault core error'],
  [282, 'cannot connect to nbvault server'],
  [283, 'error(s) occurred during vault report generation'],
  [284, 'error(s) occurred during vault report distribution'],
  [285, 'unable to locate vault directory'],
  [286, 'vault internal error'],
  [287, 'vault eject failed'],
  [288, 'vault eject partially succeeded'],
  [
    289,
    'cannot consolidate reports of sessions from container and slot-based vaults',
  ],
  [290, 'one or more errors detected during eject processing'],
  [
    291,
    'number of media has exceeded capacity of MAP; must perform manual eject using vltopmenu or vlteject',
  ],
  [292, 'eject process failed to start'],
  [293, 'eject process has been aborted'],
  [294, 'vault catalog backup failed'],
  [295, 'eject process could not obtain information about the robot'],
  [296, 'process called but nothing to do'],
  [297, 'all volumes are not available to eject'],
  [298, 'the library is not ready to eject volumes'],
  [299, 'there is no available MAP for ejecting'],
  [300, 'vmchange eject verify not responding'],
  [301, 'vmchange api_eject command failed'],
  [
    302,
    'error encountered trying backup of catalog (multiple tape catalog backup)',
  ],
  [303, 'error encountered executing Media Manager command'],
  [304, 'specified profile not found'],
  [305, 'multiple profiles exist'],
  [306, 'vault duplication partially succeeded'],
  [307, 'eject process has already been run for the requested Vault session'],
  [308, 'no images duplicated'],
  [309, 'report requested without eject being run'],
  [310, 'Updating of Media Manager database failed'],
  [311, 'Iron Mountain Report is already created for this session'],
  [312, 'invalid container database entry'],
  [313, 'container does not exist in container database'],
  [314, 'container database truncate operation failed'],
  [315, 'failed appending to container database'],
  [316, 'container_id is not unique in container database'],
  [317, 'container database close operation failed'],
  [318, 'container database lock operation failed'],
  [319, 'container database open operation failed'],
  [320, 'the specified container is not empty'],
  [321, 'container cannot hold any media from the specified robot'],
  [322, 'cannot find vault in vault configuration file'],
  [323, 'cannot find robot in vault configuration file'],
  [324, 'invalid data found in retention map file for duplication'],
  [325, 'unable to find policy/schedule for image using retention mapping'],
  [326, 'specified file contains no valid entry'],
  [327, 'no media ejected for the specified vault session'],
  [328, 'invalid container ID'],
  [329, 'invalid recall status'],
  [330, 'invalid database host'],
  [331, 'invalid container description'],
  [332, 'error getting information from EMM database'],
  [333, 'error getting information from media manager command line'],
  [334, 'unable to receive response from robot; robot not ready'],
  [335, 'failure occurred while suspending media for eject'],
  [336, 'failure occurred while updating session information'],
  [337, 'failure occurred while updating the eject.mstr file'],
  [338, 'vault eject timed out'],
  [339, 'vault configuration file format error'],
  [340, 'vault configuration tag not found'],
  [341, 'vault configuration serialization failed'],
  [342, 'cannot modify - stale view'],
  [343, 'robot already exists'],
  [344, 'vault already exists'],
  [345, 'profile already exists'],
  [346, 'duplicate MAP'],
  [347, 'vault configuration cache not initialized'],
  [348, 'specified report does not exist'],
  [349, 'incorrect catalog backup policy'],
  [350, 'incorrect vault catalog backup schedule'],
  [351, 'all configured vault steps failed'],
  [400, 'Server Group Type is Invalid'],
  [401, 'Server Group Already Exists'],
  [402, 'Server Group Already Exists with a different type'],
  [403, 'Server Group Active State is not valid'],
  [404, 'Server Group does not exist'],
  [405, "Member's server type not compatible with Server Group"],
  [406, 'The computer specified is not a member of the server group specified'],
  [407, "Member's NetBackup version not compatible with Server Group"],
  [408, 'Server Group is in use'],
  [409, 'Member already exists in server group'],
  [501, 'You are not authorized to use this application'],
  [
    502,
    'No authorization entry exists in the auth.conf file for user name username',
  ],
  [503, 'Invalid username'],
  [504, 'Incorrect password'],
  [
    505,
    'Cannot connect to the NB-Java authentication service on host on the configured port',
  ],
  [
    506,
    'Cannot connect to the NB-Java user service on host on port port_number',
  ],
  [507, 'Socket connection to the NB-Java user service has been broken'],
  [508, 'Cannot write file'],
  [509, 'Cannot execute program'],
  [510, 'File already exists: file_name'],
  [511, 'NB-Java application server interface error'],
  [512, 'Internal error'],
  [
    513,
    'bpjava-msvc: the client is not compatible with this server version (server_version)',
  ],
  [514, 'NB-Java: bpjava-msvc is not compatible with this application version'],
  [
    516,
    'Could not recognize or initialize the requested locale - (locale_NB-Java_was_started_in)',
  ],
  [
    517,
    'Cannot connect to the NB-Java user service via VNETD on host on port configured_port_number',
  ],
  [
    518,
    'No ports available in range (port_number) through (port_number) per the NBJAVA_CLIENT_PORT_WINDOW configuration option.',
  ],
  [
    519,
    'Invalid NBJAVA_CLIENT_PORT_WINDOW configuration option value: (option_value).',
  ],
  [
    520,
    'Invalid value for NB-Java configuration option (option_name): (option_value).',
  ],
  [521, 'NB-Java Configuration file (file_name) does not exist'],
  [
    522,
    'NB-Java Configuration file (file_name) is not readable due to the following error: (message).',
  ],
  [523, 'NB-Java application server protocol error'],
  [
    525,
    'Cannot connect to the NB-Java authentication service via VNETD on (host) on port (vnetd_configured_port_number).',
  ],
  [526, 'bpjava authentication service connection failed'],
  [
    527,
    'bpjava user service connection if connection to pbx on port 1556 fails',
  ],
  [538, 'unable to login'],
  [600, 'an exception condition occurred'],
  [601, 'unable to open listen socket'],
  [602, 'cannot set non blocking mode on the listen socket'],
  [603, 'cannot register handler for accepting new connections'],
  [604, 'no target storage unit specified for the new job'],
  [605, 'received error notification for the job'],
  [606, 'no robot on which the media can be read'],
  [607, 'no images were found to synthesize'],
  [608, 'storage unit query failed'],
  [609, 'reader failed'],
  [610, 'end point terminated with an error'],
  [611, 'no connection to reader'],
  [612, 'cannot send extents to bpsynth'],
  [613, 'cannot connect to read media server'],
  [614, 'cannot start reader on the media server'],
  [615, 'internal error 615'],
  [616, 'internal error 616'],
  [617, 'no drives available to start the reader process'],
  [618, 'internal error 618'],
  [619, 'internal error 619'],
  [620, 'internal error 620'],
  [621, 'unable to connect to bpcoord'],
  [622, 'connection to the peer process does not exist'],
  [623, 'execution of a command in a forked process failed'],
  [
    624,
    'unable to send a start command to a reader or a writer process on media server',
  ],
  [625, 'data marshalling error'],
  [626, 'data un-marshalling error'],
  [627, 'unexpected message received from bpsynth'],
  [628, 'insufficient data received'],
  [629, 'no message was received from bptm'],
  [630, 'unexpected message was received from bptm'],
  [631, 'received an error from bptm request to suspend media'],
  [632, 'received an error from bptm request to un-suspend media'],
  [633, 'unable to listen and register service via vnetd'],
  [634, 'no drives available to start the writer process'],
  [635, 'unable to register handle with the reactor'],
  [636, 'read from input socket failed'],
  [637, 'write on output socket failed'],
  [638, 'invalid arguments specified'],
  [639, 'specified policy does not exist'],
  [640, 'specified schedule was not found'],
  [641, 'invalid media type specified in the storage unit'],
  [642, 'duplicate backup images were found'],
  [643, 'unexpected message received from bpcoord'],
  [644, 'extent directive contained an unknown media ID'],
  [645, 'unable to start the writer on the media server'],
  [646, 'unable to get the address of the local listen socket'],
  [647, 'validation of synthetic image failed'],
  [648, 'unable to send extent message to BPXM'],
  [649, 'unexpected message received from BPXM'],
  [650, 'unable to send extent message to bpcoord'],
  [651, 'unable to issue the database query for policy'],
  [652, 'unable to issue the database query for policy information'],
  [653, 'unable to send a message to bpccord'],
  [654, 'internal error 654'],
  [655, 'no target storage unit was specified via command line'],
  [656, 'unable to send start synth message to bpcoord'],
  [657, 'unable to accept connection from the reader'],
  [658, 'unable to accept connection from the writer'],
  [659, 'unable to send a message to the writer child process'],
  [660, 'a synthetic backup request for media resources failed'],
  [661, 'unable to send exit message to the BPXM reader'],
  [662, 'unknown image referenced in the synth context message from BPXM'],
  [663, 'image does not have a fragment map'],
  [664, 'zero extents in the synthetic image, cannot proceed'],
  [665, 'termination requested by bpcoord'],
  [667, 'unable to open pipe between bpsynth and bpcoord'],
  [668, 'pipe fgets call from bpcoord failed'],
  [669, 'bpcoord startup validation failure'],
  [670, 'send buffer is full'],
  [671, 'query for list of component images failed'],
  [800, 'resource request failed'],
  [801, 'JM internal error'],
  [802, 'JM internal protocol error'],
  [803, 'JM terminating'],
  [805, 'Invalid jobid'],
  [806, 'this mpx group is unjoinable'],
  [807, 'not externalized'],
  [811, 'failed to communicate with resource requester'],
  [812, 'failed to communicate with resource broker'],
  [813, 'duplicate reference string specified'],
  [818, 'retention level mismatch'],
  [819, 'unable to communicate with JM proxy'],
  [823, 'no BRMComm to join'],
  [830, 'drive(s) unavailable or down'],
  [831, 'image has been validated'],
  [832, 'failed to write discover data to a file'],
  [833, 'error parsing discovered XML data'],
  [900, 'retry nbrb request later'],
  [901, 'RB internal error'],
  [902, 'RB invalid argument'],
  [903, 'RB communication error'],
  [904, 'RB max reallocation tries exceeded'],
  [905, 'RB media server mismatch'],
  [906, 'RB operator denied mount request'],
  [907, 'RB user canceled resource request'],
  [908, 'RB was reset'],
  [912, 'RB disk volume mount failed'],
  [914, 'RB media reservation not found'],
  [915, 'RB disk volume mount must retry'],
  [916, 'Resource request timed out'],
  [917, 'RB multiplexing group not found'],
  [
    918,
    'RB does not have a multiplexing group that uses this media ID or drive name',
  ],
  [1000, 'Client is offline'],
  [1001, 'discovery document error'],
  [1002, 'Discovery detected a failed client'],
  [1057, 'A data corruption has been detected'],
  [1058, 'A data inconsistency has been detected and corrected automatically'],
  [1401, 'Invalid arguments received'],
  [1402, 'Hold ID or Hold name argument is invalid'],
  [1403, 'Backup ID argument is invalid'],
  [1405, 'No images are found'],
  [1407, 'Invalid hold state'],
  [1408, 'Database error'],
  [1409, 'Unable to connect to database'],
  [1410, 'No data found'],
  [1411, 'Catalog error'],
  [1412, 'Hold record is being updated'],
  [1413, 'Requested hold is not found'],
  [1414, 'Duplicate hold found'],
  [1415, 'Duplicate image found'],
  [1416, 'Partially failed due to duplicate image'],
  [1417, 'Partially failed due to unhold image'],
  [1418, 'Requested image is not found'],
  [1419, 'Partially failed due to invalid image copy'],
  [1420, 'Cannot expire on hold image copy'],
  [1421, 'Active holds cannot be changed'],
  [1422, 'Cannot deassign media on hold'],
  [1423, 'Unable to retrieve hold status of the image copies'],
  [1425, 'Requested hold is not found'],
  [1426, 'Retired holds cannot be changed'],
  [1500, "Storage unit does not exist or can't be used where specified"],
  [1501, 'Source operation cannot be used where specified'],
  [1502, 'Retention type cannot be used where specified'],
  [1503, "Volume pool does not exist or can't be used where specified"],
  [1504, "Server group does not exist or can't be used where specified"],
  [
    1505,
    "alternate read server does not exist or can't be used where specified",
  ],
  [1506, 'data classification does not exist'],
  [1507, 'Invalid deferred operation flag'],
  [1508, 'Storage lifecycle policy exceeds maximum copies'],
  [1509, 'Storage lifecycle policy exceeds maximum backup operations'],
  [
    1510,
    'storage lifecycle policy cannot have more than one snapshot operation',
  ],
  [
    1511,
    'storage lifecycle policy must have at least one fixed retention or snapshot rotation operation',
  ],
  [
    1512,
    'storage lifecycle policy must have at least one backup, import, or snapshot operation',
  ],
  [1513, 'invalid priority'],
  [1514, 'invalid operation type'],
  [1515, 'Multiplexing value is not valid or cannot be used where specified'],
  [1516, 'all storage units or groups must be on the same media server'],
  [1517, 'Invalid retention level'],
  [1518, 'backup image is not supported by storage lifecycle policy'],
  [1519, 'Images are in process'],
  [1521, 'Database not available'],
  [1522, 'Error executing database query'],
  [1523, 'Invalid fragment'],
  [1524, 'Duplicate image record'],
  [1525, 'Invalid lsu'],
  [1526, 'Storage lifecycle policy exceeds maximum import operations'],
  [
    1527,
    'storage lifecycle policy can have only one of backup, import, and snapshot operations',
  ],
  [
    1528,
    'The source copy for an Auto Image Replication is not capable of replication',
  ],
  [
    1529,
    'The source copy for Auto Image Replication must specify a storage unit',
  ],
  [1530, 'Only one Auto Image Replication allowed per copy'],
  [
    1531,
    'An import storage lifecycle policy requires one copy with remote retention type',
  ],
  [
    1532,
    'Import failed because the imported image specifies an SLP name which does not exist',
  ],
  [
    1533,
    'Import failed because the imported image data class is different than the SLP data class',
  ],
  [
    1534,
    'Import failed because the imported image specifies an SLP name with no import operation',
  ],
  [
    1535,
    'Import failed because the imported image backup ID conflicts with an existing image',
  ],
  [
    1536,
    'The storage unit or storage unit group cannot be deleted because an SLP references it',
  ],
  [
    1537,
    'Backup policy and storage lifecycle policy have conflicting configurations',
  ],
  [1538, 'Data classification in the SLP conflicts with backup policy'],
  [
    1539,
    'Backup policy generates snapshots but storage lifecycle policy does not handle them',
  ],
  [
    1540,
    'SLP expects snapshots but backup policy does not create them with SLP management enabled',
  ],
  [1541, 'Snapshot creation failed'],
  [
    1542,
    'An existing snapshot is no longer valid and cannot be mounted for subsequent operations',
  ],
  [1543, 'Policy type is not compatible with SLP operations'],
  [1545, 'Schedule type is not compatible with SLP operations'],
  [
    1546,
    'Capacity managed retention type is not compatible with SLP operations',
  ],
  [1547, 'Expire after copy retention requires a dependent copy'],
  [1548, 'Retention type is not compatible with snapshot operation'],
  [1549, 'TIR information selection is not compatible with SLP operations'],
  [
    1552,
    'The source and target storage units are not valid replication partners.',
  ],
  [1553, 'Checkpoints are not allowed with SLP operations'],
  [
    1554,
    'Storage unit snapshot capability is not compatible with operation characteristics',
  ],
  [1556, 'The SLP deletion failed because a backup policy refers to it'],
  [
    1557,
    'Must specify mirror retention when target storage unit is mirror capable.',
  ],
  [
    1558,
    'Mirror retention is not allowed when target storage unit is not mirror capable.',
  ],
  [1559, 'SLP referenced in policy or schedule not found'],
  [
    1560,
    'Fixed or rotation retention required without a replication operation',
  ],
  [
    1561,
    'Policy using NDMP conflicts with multiple Backup From Snapshot operations in storage lifecycle policy',
  ],
  [
    1562,
    'Backup schedule generates snapshots but storage lifecycle policy does not handle them',
  ],
  [1563, 'SLP expects snapshots but backup schedule does not create them'],
  [1564, 'Storage lifecycle policy contains errors'],
  [
    1565,
    'Policy snapshot method is not compatible with SLP snapshot operations',
  ],
  [
    1566,
    'Storage unit required for snapshot operation when no other operation present',
  ],
  [1567, 'Only one NDMP backup of a snapshot per backup ID is allowed'],
  [
    1568,
    'Only one Index From Snapshot operation is allowed per storage lifecycle policy',
  ],
  [
    1569,
    'Snapshot storage unit is not configured for primary snapshots. It cannot be used in snapshot operation.',
  ],
  [1570, 'Policy type does not support Index from Snapshot'],
  [
    1571,
    'Data mover type specified in policy does not support Index from Snapshot',
  ],
  [1572, 'Storage unit must be specified for this operation'],
  [
    1573,
    'Backup image cannot be expired because its SLP processing is not yet complete',
  ],
  [
    1574,
    "Data Classification name cannot be 'Any' while creating new data classification",
  ],
  [1575, 'Data Classification auto creation failed'],
  [1576, 'Topology validation failed'],
  [
    1577,
    'Storage unit in the SLP does not match the accelerator attribute in policy',
  ],
  [1578, 'Invalid window close options'],
  [1579, 'One or more images were not processed because the window closed'],
  [1580, 'VMware policy with PFI enabled requires an SLP'],
  [
    1581,
    'Non-application consistent VMware policy is not compatible with snapdupe operations',
  ],
  [1582, 'Application consistent VMware policy requires VM quiesce'],
  [1583, 'VMware policy with PFI enabled requires VIP auto discovery'],
  [
    1584,
    "VMware policy with 'Persistent Frozen Image' enabled requires schedule type of Full Backup",
  ],
  [
    1585,
    'Backup image cannot be expired because not all dependent copies are expired',
  ],
  [1586, 'SLP operation was canceled'],
  [
    1587,
    'Storage lifecycle policy cannot have both target and untarget replication to remote master',
  ],
  [
    1588,
    'Target master server is already used in one of the replications to remote master',
  ],
  [1589, 'Cannot connect to specified target master server'],
  [1590, 'Cannot find specified target import SLP'],
  [1591, 'No import SLP(s) found with compatible replication target device'],
  [
    1592,
    'Trusted master servers are being referred by one or more Storage Lifecycle Policies on the source or target domain',
  ],
  [1593, 'Replication Director for VMware policy requires mapped backups'],
  [1594, 'Failed to determine disk media ID'],
  [
    1596,
    "Select a storage lifecycle policy that has no snapshot operation as a policy's Storage Destination",
  ],
  [1597, 'Replication Director for Oracle policy requires an SLP'],
  [1598, 'Oracle policy with PFI and FI enabled requires an SLP'],
  [1599, 'Application schedule storage selection cannot be a snapshot SLP'],
  [
    1600,
    'The Policy storage is a snapshot SLP and the Application schedule does not override the policy storage selection.',
  ],
  [1601, 'Full schedule requires a snapshot SLP'],
  [
    1602,
    'The Policy storage is not a snapshot SLP and the Full schedule does not override the policy storage selection.',
  ],
  [1603, 'Failed to save target SLP volume information'],
  [1604, 'No import SLP(s) found with compatible data class'],
  [1800, 'Invalid client list'],
  [
    1915,
    'Cannot delete instance group that contains instances (delete or move instances first)',
  ],
  [1916, 'Database error, cannot access the instance repository'],
  [1917, 'Cannot add instance group, this group name is already in use'],
  [1918, 'Cannot find a group by this name'],
  [
    1919,
    'This instance or instance group was modified by another process, refresh before editing',
  ],
  [1920, 'An instance with this name and client already exists'],
  [1921, 'The specified instance cannot be found'],
  [1924, 'Domain is a required field for Windows instances'],
  [1925, 'The requested operation(s) failed'],
  [1926, 'The entry specified already exists'],
  [1927, 'The entry specified does not exist'],
  [1928, 'The credentials for 1 or more instances could not be verified'],
  [
    2000,
    'Unable to allocate new media for backup, storage unit has none available.',
  ],
  [2001, 'No drives are available for this job'],
  [2002, 'Invalid STU identifier type'],
  [2003, 'Drive is not allocated'],
  [2004, 'Drive is already allocated'],
  [2005, 'MDS has received an invalid message from a media server'],
  [2006, 'NDMP credentials are not defined in EMM'],
  [2007, 'Storage unit is not compatible with requesting job'],
  [2008, 'All compatible drive paths are down'],
  [2009, 'All compatible drive paths are down but media is available'],
  [2010, 'Job type is invalid'],
  [2011, 'The media server reported a system error'],
  [2012, 'Media has conflicts in EMM'],
  [2013, 'Error record insert failed'],
  [2014, 'Media is not assigned'],
  [2015, 'Media is expired'],
  [2016, 'Media is assigned to another server'],
  [2017, 'Media needs to be unmounted from a drive'],
  [2018, 'Number of cleanings is invalid'],
  [2019, 'Media is in a drive that is not configured on local system'],
  [2020, 'Robotic library is down on server'],
  [2021, 'Allocation record insert failed'],
  [2022, 'Allocation status record insert failed'],
  [2023, 'Allocation identifier is not known to EMM'],
  [2024, 'Allocation request update failed'],
  [2025, 'Allocation request delete failed'],
  [2026, 'Allocation status request delete failed'],
  [2027, 'Media server is not active'],
  [2028, 'Media is reserved'],
  [2029, 'EMM database is inconsistent'],
  [2030, 'Insufficient disk space or high water mark would be exceeded'],
  [2031, 'Media is not defined in EMM'],
  [2032, 'Media is in use according to EMM'],
  [2033, 'Media has been misplaced'],
  [2034, 'Retry the allocation request later'],
  [2035, 'Request needs to pend'],
  [2036, 'Drive is in a robotic library that is up'],
  [2037, 'Drive is not ready'],
  [2038, 'Media loaded in drive is not write-enabled'],
  [2039, 'SCSI reservation conflict detected'],
  [2040, 'Maximum job count has been reached for the storage unit'],
  [2041, 'Storage unit is down'],
  [2042, 'Density mismatch detected'],
  [2043, 'Requested slot is empty'],
  [2044, 'Media is assigned to another application'],
  [2045, 'Storage unit is disabled since max job count is less than 1'],
  [2046, 'Media is unmountable'],
  [2047, 'Media is write protected'],
  [2048, 'Media is in use by the ACS robotic library'],
  [2049, 'Media not found in the ACS robotic library'],
  [2050, 'ACS media has an unreadable external label'],
  [2051, "ACS media is not in the drive's domain"],
  [2052, 'An ACS Library Storage Module (LSM) is offline'],
  [2053, 'Media is in an inaccessible drive'],
  [2054, 'Media is in a drive that is currently in a DOWN state'],
  [2055, 'ACS physical drive is not available'],
  [2056, 'The file name used for the mount request already exists'],
  [2057, 'The scan host of the drive is not active'],
  [
    2058,
    'LTID needs to be restarted on media servers before the device can be used',
  ],
  [2059, 'The robotic library is not available'],
  [2060, 'Media needs to be rewound or unmounted from a drive'],
  [2061, 'The host is not an active node of a cluster'],
  [2062, 'Throttled job count has been reached for the storage unit'],
  [2063, 'Server is not licensed for the Remote Client Option'],
  [2064, 'Job history indicates that no media is available'],
  [2065, 'Job history indicates that no drive is available'],
  [2066, 'Disk pool not found'],
  [2067, 'Disk volume not found'],
  [2068, 'Disk volume mount point not found'],
  [2069, 'Disk volume mount point record insert failed'],
  [2070, 'The specified mount path will not fit in the allocated space'],
  [2071, 'Unable to find any storage servers for the request'],
  [2072, 'Invalid operation on static mount point'],
  [2073, 'Disk pool is down'],
  [2074, 'Disk volume is down'],
  [2075, 'Fibre Transport resources are not available'],
  [2076, 'DSM returned an unexpected error'],
  [2078, 'The maximum number of mounts for the disk volume have been exceeded'],
  [
    2079,
    'DSM has detected that an invalid file system is mounted on the volume',
  ],
  [2080, 'Disk volume has no max writers count'],
  [2081, 'Disk volume has no max readers count'],
  [2082, 'The drive needs to be marked as available'],
  [2083, 'The media affinity group is not defined in EMM'],
  [2084, 'Media affinity group record insert failed'],
  [2085, 'Disk volume is not available'],
  [2086, 'Disk volume cannot be used for more than one copy in the same job'],
  [2087, 'Media allocation would exceed maximum partially full media limit'],
  [2088, 'Cleaning media is not available'],
  [2089, 'FT client is not running'],
  [2090, 'FT client has no devices configured'],
  [2091, 'FT client devices are offline'],
  [2092, 'FT server devices for client are offline'],
  [2093, 'No FT servers for this client are running'],
  [2094, 'STU cannot run Lifecycle backups'],
  [2095, 'STU cannot run VMWare backup'],
  [2096, 'NDMP operation does not support multiple inline copies'],
  [2097, 'Storage Unit group does not exist in EMM configuration'],
  [2098, 'Media pool is not eligible for this job'],
  [2099, 'Required drive or drive path is not configured'],
  [2100, 'Maximum number of mounts has been exceeded for tape media'],
  [2101, 'Media server not found in EMM database'],
  [2102, 'Storage unit does not support spanning'],
  [2103, 'Media server mismatch'],
  [2104, 'Storage units are not available'],
  [
    2105,
    'Storage unit requested for replication job is not replication capable',
  ],
  [2106, 'Disk storage server is down'],
  [
    2107,
    'Requested media server does not have credentials or is not configured for the storage server',
  ],
  [
    2108,
    'Requested NDMP machine does not have credentials or is not configured in NetBackup',
  ],
  [
    2109,
    'Requested Fibre Transport client machine was not found in NetBackup configuration',
  ],
  [2110, 'Requested machine is not configured in NetBackup'],
  [
    2111,
    'All storage units are configured with On Demand Only and are not eligible for jobs requesting ANY storage unit',
  ],
  [2112, 'NetBackup media server version is too low for the operation'],
  [2113, 'Invalid or no disk array credentials are added for vserver'],
  [2504, 'Direct expiration of a mirror copy is not allowed'],
  [2517, 'Backup set identifier may only contain a-z, A-Z, 0-9 and .-+_'],
  [2521, 'Datafile copy tag may only contain a-z, A-Z, 0-9 and .-+_'],
  [
    2522,
    'Oracle policy cannot include a pluggable database with a FRA backup.',
  ],
  [2800, 'Standard policy restore error'],
  [2801, 'Oracle policy restore error'],
  [2802, 'Informix-On-BAR policy restore error'],
  [2803, 'Sybase policy restore error'],
  [2804, 'MS-SharePoint policy restore error'],
  [2805, 'MS-Windows policy restore error'],
  [2806, 'NetWare policy restore error'],
  [2807, 'SQL-BackTrack policy restore error'],
  [2808, 'Windows File System policy restore error'],
  [2809, 'MS-SQL-Server policy restore error'],
  [2810, 'MS-Exchange policy restore error'],
  [2811, 'SAP policy restore error'],
  [2812, 'DB2 policy restore error'],
  [2813, 'NDMP policy restore error'],
  [2814, 'FlashBackup policy restore error'],
  [2815, 'AFS policy restore error'],
  [2816, 'DataStore policy restore error'],
  [2817, 'FlashBackup Windows policy restore error'],
  [2818, 'NetBackup Catalog policy restore error'],
  [2819, 'Enterprise Vault policy restore error'],
  [2820, 'NetBackup VMware policy restore error'],
  [2821, 'Hyper-V policy restore error'],
  [
    2826,
    'Master server failed to connect to backup restore manager on media server for restore',
  ],
  [2827, 'Client failed to connect to the media server for restore'],
  [2828, 'Restore failed because the MS-SQL-Server services are down'],
  [2829, 'Restore failed due to MS-SQL-Server database in use'],
  [
    2830,
    'Restore failed due to an incorrect path in the MS-SQL-Server MOVE script',
  ],
  [2831, 'Restore error'],
  [2832, 'Restore failed due to rename file format error'],
  [2833, 'Restore failed due to partition restore error'],
  [2834, 'Restore failed due to failure to read change block bit map'],
  [2835, 'Restore failed due to corrupt image'],
  [
    2836,
    'Restore failed because the bitmap size read from the image header differs from the expected size.',
  ],
  [2837, 'Restore failed due to invalid metadata'],
  [2838, 'Restore failed because no raw partitions were found'],
  [2839, 'Restore failed due to invalid raw partition id'],
  [2840, 'Restore failed due to out of sequence raw partitions'],
  [
    2841,
    'Restore failed due to failure to read the header from the backup image',
  ],
  [2842, 'Restore failed due to failure to read the VMware bitmap'],
  [2843, 'Restore failed due to failure to start VxMS'],
  [2844, 'Restore failed due to failure to read the FIID file'],
  [2845, 'Restore failed due to failure to retrieve the bitmap'],
  [2846, 'Restore failed due to failure to retrieve the fsmap'],
  [2847, 'Restore failed due to failure to start the bptm writer'],
  [2848, 'Restore failed due to failure to create the virtual machine'],
  [
    2849,
    'Restore failed due to failure to delete the virtual machine snapshot',
  ],
  [2850, 'Restore error'],
  [4200, 'Operation failed: Unable to acquire snapshot lock'],
  [
    4201,
    'Incorrect snapshot method configuration or snapshot method not compatible for protecting backup selection entries',
  ],
  [4202, 'Invalid or incompatible storage unit configured'],
  [4203, 'Invalid or unsupported backup selection filelist'],
  [4204, 'Incompatible client found'],
  [4205, 'Incorrect or no credentials found'],
  [
    4206,
    'Authentication error occurred. NetBackup Client Service is running as Local System, this is likely incorrect.',
  ],
  [4207, 'Could not fetch snapshot metadata or state files'],
  [4208, 'Could not send snapshot metadata or statefiles'],
  [4209, 'Snapshot metadata or statefiles cannot be created'],
  [4210, 'Incorrect or no content found in snapshot metadata'],
  [4211, 'Snapshot not accessible or invalid snapshot'],
  [4212, 'Recreation of snapshot failed'],
  [4213, 'Snapshot import failed'],
  [4214, 'Snapshot mount failed'],
  [4215, 'Snapshot deletion failed'],
  [4216, 'Snapshot cleanup failed'],
  [4217, 'Snapshot restore failed'],
  [4218, 'Snapshot deport failed'],
  [
    4219,
    'Command operation failed: Third-party command or API execution failed',
  ],
  [4220, 'Command operation failed: System command or API execution failed'],
  [4221, 'Found an invalid or unsupported configuration'],
  [4222, 'Operation failed: Unable to acquire policy lock to take snapshot'],
  [4223, 'Operation not completed'],
  [4224, 'STS Internal Error'],
  [
    4225,
    'Unauthorized operation attempted by client or media on storage server',
  ],
  [4226, 'Communication failure occurred with storage server'],
  [4227, 'STS Plugin error occurred'],
  [4228, 'Storage server or plugin version mismatch'],
  [4229, 'Insufficient resources or capabilities found by storage server'],
  [4230, 'Invalid storage topology or storage server configuration error'],
  [4231, 'STS Unexpected Error'],
  [4232, 'Invalid Discovery Query URI'],
  [4233, 'BIOS uuid client reference not allowed for vCloud'],
  [4234, 'VMware server login failure'],
  [4235, 'vCloud keyword used when vCloud not enabled'],
  [4236, 'vCloud policy includes multiple organizations'],
  [4237, 'Client does not meet policy requirements'],
  [4238, 'No server credentials configured for policy'],
  [4239, 'Unable to find the virtual machine'],
  [4240, 'Operation not supported'],
  [4243, 'Unable to connect to the VirtualCenter server'],
  [4245, 'Invalid pathname for backup selection'],
  [4246, 'The requested operation was partially successful'],
  [
    4247,
    'Index from snapshot for Replication Director NDMP Policy is not supported on AIX media server',
  ],
  [4248, 'Index from snapshot operation failed with an internal error'],
  [4249, 'Index from snapshot operation failed, catalog already exists'],
  [
    4250,
    'Index from snapshot operation failed, unable to find child image or file information',
  ],
  [
    4251,
    'Index from snapshot operation failed. Failed to write into index database.',
  ],
  [
    4252,
    'Index from snapshot operation failed. Entry does not belong to any of the backup selection entries.',
  ],
  [
    4253,
    'Index from snapshot operation failed. SLP version mismatch for current and previous backup image.',
  ],
  [4254, 'Invalid or no path found to create index database'],
  [4255, 'Index from snapshot using snapdiff is disabled by the user'],
  [
    4256,
    'Index from snapshot is not supported for the filesystem associated with backup selection',
  ],
  [4257, 'Index from snapshot is not supported for the storage server'],
  [4258, 'Transient error encountered while taking Hyper-V VM snapshot'],
  [4259, 'Failed to find Virtual Center hostname in VMware Lookup Service'],
  [4260, 'Encountered SSO login failure'],
  [4261, 'Encountered VMware Internal Server Error'],
  [4262, 'Encountered VMware vCloud Suite API failure'],
  [4263, 'Encountered VMware SOAP API failure'],
  [4264, 'Encountered unexpected error while processing TagView XML'],
  [
    4265,
    'Encountered a VMware Virtual Machine Server that does not support Tags',
  ],
  [
    4266,
    'Encountered a VMware Virtual Machine Server that does not offer Tag APIs',
  ],
  [4267, 'Failed to initialize Java runtime environment'],
  [4268, 'Failed to retrieve resource pool information'],
  [4269, 'Found multiple virtual machines with same identity'],
  [
    4270,
    'A snapshot of the virtual machine exists and the policy option specifies aborting the backup',
  ],
  [4271, 'Maximum virtual machine snapshots exceeded'],
  [4272, 'Maximum delta files exceeded'],
  [
    4273,
    'Unable to lock the backup or restore host for virtual machine snapshot operations',
  ],
  [4274, 'Failed to remove virtual machine snapshot'],
  [4275, 'Unable to consolidate Virtual Machine Disks'],
  [4276, 'Unable to retrieve Virtual Machine Disk information'],
  [4277, 'Virtual machine path contains unsupported characters'],
  [4278, 'Unable to retrieve virtual machine information'],
  [4279, 'Unable to retrieve virtual machine vCloud information'],
  [
    4280,
    'Virtual machine contains independent and Raw Device Mapping disks only',
  ],
  [4281, 'Virtual machine contains independent disks only'],
  [4282, 'Virtual machine contains Raw Device Mapping disks only'],
  [4283, 'Error detected while processing disk identifiers'],
  [
    4287,
    'A NetBackup snapshot of the virtual machine exists and the policy option specifies aborting the backup',
  ],
  [
    5400,
    'Backup error - None of the request objects were found in the database',
  ],
  [
    5401,
    'Backup error - FRA (Fast Recovery Area) was requested, but it was not found in the database',
  ],
  [
    5402,
    'OS Authentication error - Could not connect to the database. Please check the OS credentials',
  ],
  [
    5403,
    'Oracle Authentication error - Could not connect to the database. Please check the Oracle credentials',
  ],
  [5404, 'ASM validation error - PROXY backup is not supported for ASM'],
  [
    5405,
    'Recovery Catalog Authentication error - Could not connect to the Recovery Catalog.',
  ],
  [
    5406,
    'Archive log only backup requested, but database is not in ARCHIVELOG Mode',
  ],
  [
    5407,
    'Database is in the wrong state (must be OPEN) for the requested action',
  ],
  [5408, 'OS Authentication error - Could not find credentials'],
  [5409, 'Cloning is NOT supported for this client platform'],
  [5410, 'Oracle Intelligent Policy is NOT supported for this client platform'],
  [5411, 'Cannot do a hot backup of a database in NOARCHIVELOG mode'],
  [
    5412,
    'Database is in the wrong state (must be OPEN or MOUNTED) for an Archive Log Backup',
  ],
  [
    5413,
    'Database is in the wrong state (must be OPEN or MOUNTED) for an FRA backup',
  ],
  [5414, 'The request operation is not supported with this client version'],
  [5415, 'Cannot shut down read-only standby database'],
  [5416, 'Oracle could not resolve the TNS connection identifier'],
  [5417, 'An error has occurred checking if the NFS server is an appliance'],
  [5418, 'The NFS server is not an appliance'],
  [
    5419,
    'The database backup share directory is not available on the appliance.',
  ],
  [
    5420,
    'Whole Database - Datafile Copy Share selection is not supported for this client platform.',
  ],
  [5421, 'None of the requested pluggable databases were found'],
  [
    5422,
    'Partial success - one or more of the requested pluggable databases were not found.',
  ],
  [
    5423,
    'None of the requested tablespaces were found in the requested pluggable databases.',
  ],
  [
    5424,
    'Partial success - one or more of the requested pluggable databases did not contain any of the requested tablespaces.',
  ],
  [
    5425,
    'None of the requested data files were found in the requested pluggable databases.',
  ],
  [
    5426,
    'Partial success - one or more of the requested pluggable databases did not contain any of the requested data files.',
  ],
  [5427, 'Partial success - more than one error was encountered'],
  [5428, 'No database backup shares were found'],
  [
    5429,
    'No files that are related to the instance or database were found in the database backup share.',
  ],
  [
    5430,
    'Database must be in ARCHIVELOG mode to perform a cold backup of a pluggable database.',
  ],
  [5500, 'The NetBackup core web service service internal error'],
  [5501, 'Supplied URI is too short'],
  [5502, 'Supplied URI is not supported'],
  [5503, 'NetBackup core web service is terminating'],
  [5504, 'Query string in URI is bad'],
  [5505, 'Client name is required'],
  [5506, 'Failed to communicate with core web service proxy'],
  [5507, 'Unknown jobid'],
  [5508, 'Error in parsing XML document'],
  [5761, 'Failed to initialize Windows Socket library'],
  [5762, 'Peer is not a NetBackup Master or Media Server'],
  [5763, 'Encountered error during socket communication'],
  [5764, 'Command specified for execution is invalid or not allowed'],
  [5765, 'Failed to execute specified command (CreateProcess or exec)'],
  [5766, 'Failed to execute specified command (fork)'],
  [5767, 'Failed to get exit code of child process'],
  [5768, 'Failed to read complete output of executed command'],
  [5769, 'Failed to reap exit code of child process'],
  [5770, 'Failed to get cluster configuration'],
  [5771, 'Failed to write output received from remote command'],
  [5772, 'Failed to read unified logging configuration file'],
  [5773, 'Failed to get virtual name of Master Server'],
  [5774, 'Specified logs are not valid'],
  [5775, 'Invalid option specified'],
  [5776, 'Failed to spawn new process'],
  [5777, 'Failed to create staging directory on Master Server'],
  [5778, 'Failed to read Logging Assistant database'],
  [5779, 'Failed to lock Logging Assistant database'],
  [5780, 'Failed to set non-inherit flag on database file handle'],
  [5781, 'Failed to prepare to save Logging Assistant database'],
  [5782, 'Failed to start to write Logging Assistant database'],
  [5783, 'Failed to save Logging Assistant database'],
  [5784, 'Failed to access or write the readme or progress file'],
  [5785, 'FTP connection failed'],
  [5786, 'Logging Assistant record does not exist'],
  [5787, 'Logging Assistant record already exists'],
  [5788, 'Debug logging has not been set up for Logging Assistant record'],
  [5789, 'Failed to interpret bpdbjobs output for job detail'],
  [
    5790,
    'Failed to fetch PureDisk configuration setting from Windows registry',
  ],
  [5794, 'Failed to calculate debug logs size for preview'],
  [5795, 'Upload evidence directory does not exist'],
  [
    5796,
    'Logging Assistant agent encountered failure writing on socket to Master Server',
  ],
  [5797, 'Failed to upload file to FTP server'],
  [5798, 'Failed to list disk volumes on Master Server using bpmount'],
  [5799, 'Failed to get disk space information of volumes or mount points'],
  [5800, 'Failed to execute bpdbjobs to fetch job details'],
  [5801, 'Failed to fetch job details. Check if job exists'],
  [5802, 'Unknown ftp server location specified'],
  [5803, 'Failed to modify PureDisk configuration file'],
  [5804, 'Failed to modify Java GUI configuration file (Debug.properties)'],
  [5805, 'Remote host NetBackup version not supported by Logging Assistant'],
  [5806, 'Unexpected contents of PureDisk configuration file (pdregistry.cfg)'],
  [5807, 'Failed to copy nbcplogs/nbsu output file from remote host'],
  [5808, 'Failed to load PBX configuration to change log level'],
  [5809, 'Invalid PBX Debug Log Level specified'],
  [5810, 'No files to upload in specified directory'],
  [5811, 'Temporary directory to use for logs collection does not exist'],
  [5812, 'nbcplogs exited with error'],
  [5813, 'nbcplogs did not collect any logs'],
  [5814, 'nbsu exited with error'],
  [5815, 'No activity for the Logging Assistant record is in progress'],
  [5816, 'Collect and upload debug logs operation canceled'],
  [5817, 'Collect and upload nbsu operation canceled'],
  [5818, 'Upload evidence operation canceled'],
  [5819, 'Cancel operation requested'],
  [5820, 'Not a valid Logging Assistant temporary directory for clean-up'],
  [5821, 'Failed to get policy details'],
  [6000, 'The provided path is not whitelisted'],
]);
